#!/usr/bin/with-contenv bash
"${STEAMCMD_DIR}/steamcmd.sh" +login anonymous +force_install_dir "/app/${STEAM_APP_NAME}" +app_update $STEAM_APP_ID validate +quit
chown -R abc:abc "/app/${STEAM_APP_NAME}"
